// MENU HAMBÚRGUER
document.getElementById("btn-menu").addEventListener("click", function () {
    const menu = document.getElementById("menu-list");
    menu.style.display = menu.style.display === "flex" ? "none" : "flex";
});

// SLIDESHOW
let imagens = [
    "img/foto1.jpg",
    "img/foto2.jpg",
    "img/foto3.jpg"
];

let index = 0;

function mostrarImagem() {
    document.getElementById("slide").src = imagens[index];
}

function avancar() {
    index = (index + 1) % imagens.length;
    mostrarImagem();
}

function voltar() {
    index = (index - 1 + imagens.length) % imagens.length;
    mostrarImagem();
}

// TEXTOS DAS REDAÇÕES
let redacoes = [
    {
        titulo: "A Busca pela beleza na sociedade moderna",
        texto: "Na sociedade atual vem se tornado alvo de debates entre as pessoas o crescente aumento da busca por procedimentos estéticos pelo público jovem Isso demonstra um grande problema em nossa sociedade moderna, onde essa alta demanda é reflexo de uma busca por padrões de beleza perfeitos e aversão a si mesmo, e, mesmo com possíveis consequências desses procedimentos a procura não diminui e só aumenta, produto da popularização da internet e das redes sociais, uma era digital, um mundo inteiro de comparação e julgamento, onde a vaidade toma conta convidando inveja e orgulho para a festa. Esse desejo de alterar a própria imagem que se vê no reflexo do espelho pode causar consequências, além do aspecto psicológico das pessoas afetadas por essa comparação e desgosto próprio, em casos de problemas em procedimentos cirúrgicos ou possíveis outros problemas, deformações físicas podem surgir e 'afundar' ainda mais a pessoa no mar do ego. Tal questão deve ser abordada com seriedade por nós como sociedade, nos prendemos em padrões de beleza irreais, lutamos contra o próprio tempo ao tentar reverter o envelhecimento e acabamos fazendo mal a nós mesmos, é certo continuar nesse ciclo de ver e invejar? O que tem de tão feio em nós que nos impulsiona a buscar ser mais e nos afundar em ego? Isso é realmente o que queremos? Lembre-se, você é lindo do jeito que você é!!!"
    },
    {
        titulo: "Inclusão de pessoas com deficiência",
        texto: "A acessibilidade e a inclusão de pessoas com deficiência no Brasil ainda representam um desafio social e estrutural. Apesar de avanços legais, como a Lei Brasileira de Inclusão(LBI), muitos espaços públicos e privados permanecem inadequados, dificultando o acesso à educação, ao trabalho e à mobilidade urbana. A falta de rampas, sinalização adequada e recursos tecnológicos adaptados são exemplos de barreiras enfrentadas diariamente. Além da infraestrutura, a inclusão também depende de mudanças culturais. O preconceito e a desinformação ainda limitam a plena participação dessas pessoas na sociedade. É essencial promover a conscientização, o respeito às diferenças e a valorização das potencialidades individuais. Investir em políticas públicas eficazes, fiscalizar o cumprimento das leis e promover a educação inclusiva são passos fundamentais. A construção de uma sociedade verdadeiramente acessível e igualitária exige esforço conjunto do governo, da iniciativa privada e da população, garantindo dignidade e oportunidade para todos os cidadãos, com ou sem deficiência."
    },
    {
        titulo: "O que influencia em nossa qualidade de vida e bem-estar ",
        texto: "O bem-estar e a qualidade de vida são conceitos muito parecidos e também importantíssimos para a nossa vida como seres-humanos, ambos representam o nosso nível de satisfação pessoal geral(bem-estar), e satisfação com a nossa vida e situação(qualidade de vida), de modo que são uma das causas que afetam diretamente a nossa saúde, afinal, saúde não é apenas não estar doente, mas também estar com uma saúde mental estável e manter relações sociais boas. Sendo assim, surge uma questão: O que pode influenciar meu bem-estar e qualidade de vida? Entre esses fatores, podemos começar com um bem importante, as amizades e conexões emocionais, que nada mais e nada menos são que as nossas relações sociais, que, como seres sociais não podemos ficar sem, também como vivemos a nossa rotina, se realizamos atividades físicas regularmente ou algum hobby, importante lembrar ainda obviamente o fator financeiro, que é essencial para, por exemplo, se alimentar, locomover-se, e entre outras muitas coisas."
    },
    {
        titulo: "Impacto das Mudanças Climáticas no Brasil",
        texto: "As mudanças climáticas são um problema que afetam e vão afetar ainda mais a vida dos brasileiros, como afirma o IPCC(Painel Intergovernamental sobre Mudanças Climáticas), caso medidas não forem tomadas, a temperatura pode exceder até em 2° celsius os níveis pré-industriais até 2100. E como isso pode nos afetar? Bem, quando falamos de impactos climáticas é importante lembrar que nos referimos a como isso afeta a vida das pessoas e o seu ambiente, por exemplo a agricultura, o fazendeiro precisa ficar atento a quantidade de luz do sol e de água para conseguir plantar, fatores que podem ser desequilibrados por mudanças climáticas. Algo simplesmente chocante é que países tropicais como o Brasil, serão os que mais serão afetados, com maior número de inundações pela grande ocorrência de tempestades, aumento do nível do mar(derretimento das geleiras), e períodos de estiagem, tudo isso afetará a agricultura e a pecuária no país e no mundo. Outro agravamento será a intensificação de chuvas que implicarão no aumento nos deslizamentos e enchentes, e o clima ficando mais seco será propicio para incêndios e secas, contribuindo para tornar a água potável, um tesouro ainda maior do que já é, tornando-se provavelmente um grande causador de guerras as fontes de água limpa. O aquecimento global é um dos grandes motivos para isso, já que é o processo que regula a temperatura do planeta ao absorver energia da luz solar e transformar em calor, porém, devido aos humanos cada vez mais liberarem gases na atmosfera em níveis nunca antes vistos, resulta na maior absorção térmica pelo processo, aumentando a temperatura mundial, para combater esse processo é necessária a adoção de políticas ambientais pelos governos, para combater a poluição do ar e do desmatamento da natureza, ações que estão a cada dia nos condenando a um mundo mais quente."
    },
    {
        titulo: "Lixo eletrônico e a poluiçao do meio ambiente",
        texto: "Cada vez mais o descarte inadequado de lixo eletrônico vem aumentado, superando em muito a marca de 44,7 milhões de metros cúbicos de lixo em 2016, o que impulsiona a poluição do meio ambiente pelo descarte de todo essa material muitas vezes até de forma inadequada. Tal ação pode nos afetar de diversas maneiras, o intenso número desses materiais pode afetar o meio ambiente desde o início da cadeia alimentar até chegar ao topo dela, e consequente seremos atingidos também por essa contaminação, afinal, os eletrônicos que usamos são feitos de materiais radioativos. Alguns podem argumentar que é besteira, e que esses materiais sempre estiveram na terra, e nunca deu problema, por que aconteceria agora algum não é? Podendo propor que a solução seria simples como apenas enterrá-lo e que a natureza cuidaria do resto, mas não é bem assim, os materiais de fato já existiam, mas em pequenas quantidades e bem abaixo do solo, milhares de toneladas destes materiais na superfície é um problema catastrófico, causando desde a poluição até o aumento na propagação dos gases do efeito estufa, ou seja, mesmo o aquecimento global também é influenciado por isso. Ou seja, é essencial que o mundo acorde para o problema que vem batendo em nossa parte, avanços tecnológicos que produzam aparelhos mais duráveis são uma opção, mas principalmente devemos fazer nossa parte e reciclar e descartar bem o lixo, se informem das maneiras corretas e como fazer, não o misture com outros tipos de lixo e não os use excessivamente."
    },
    {
        titulo: "Ultraprocessados no dia a dia",
        texto: "Não é novidade para nínguem que os jogos de azar sempre movimentaram grandes quantidades de dinheiro e atraíram inúmeros jogadores com promessas de fortuna rápida mas com perigos escondidos(vícios e falências), porém, no século xxi, com o desenvolvimento das tecnologias digitais, surgiu um método de apostas muito mais acessível para a população, que são as apostas onlines através de sites ou aplicativos Com isso, o problema que antes já era terrível, ganhou um nível ainda maior de abrangência e complexidade, através das mídias esses sites ganharam fama e começaram a ser utilizados pela população, alguns atrás de renda fácil e solucionar problemas se juntaram à prática, ocasionando uma explosão no número de casas de apostas online, fazendo com que o impacto dessas na sociedade fosse amplificado em muitas vezes, com muitos jogadores perdendo tudo, desde dinheiro até relacionamentos por viciar-se nas apostas Tal comportamento tem se tornado mais comum a cada dia que passa, pessoas que ficam sem comer ou moradia para realizar apostas, isso se deve também às grandes propagandas publicitárias, com a participação de famosos influentes que acabam impulsionando a onda de acessos aos sites A situação mostra-se crítica e é indispensável que medidas sejam tomadas, o governo deve tomar medidas mais rigorosas e agir em defesa do público mais vulnerável, como jovens e pessoas em situações financeiras críticas, além de fiscalizar as casas de apostas e suas propagandas para que isso não fique mais profundo em nossa sociedade"
    },
    {
        titulo: "O Problema Das Apostas online",
        texto: "Não é novidade para nínguem que os jogos de azar sempre movimentaram grandes quantidades de dinheiro e atraíram inúmeros jogadores com promessas de fortuna rápida mas com perigos escondidos(vícios e falências), porém, no século xxi, com o desenvolvimento das tecnologias digitais, surgiu um método de apostas muito mais acessível para a população, que são as apostas onlines através de sites ou aplicativos Com isso, o problema que antes já era terrível, ganhou um nível ainda maior de abrangência e complexidade, através das mídias esses sites ganharam fama e começaram a ser utilizados pela população, alguns atrás de renda fácil e solucionar problemas se juntaram à prática, ocasionando uma explosão no número de casas de apostas online, fazendo com que o impacto dessas na sociedade fosse amplificado em muitas vezes, com muitos jogadores perdendo tudo, desde dinheiro até relacionamentos por viciar-se nas apostas Tal comportamento tem se tornado mais comum a cada dia que passa, pessoas que ficam sem comer ou moradia para realizar apostas, isso se deve também às grandes propagandas publicitárias, com a participação de famosos influentes que acabam impulsionando a onda de acessos aos sites A situação mostra-se crítica e é indispensável que medidas sejam tomadas, o governo deve tomar medidas mais rigorosas e agir em defesa do público mais vulnerável, como jovens e pessoas em situações financeiras críticas, além de fiscalizar as casas de apostas e suas propagandas para que isso não fique mais profundo em nossa sociedade"
    },
    {
        titulo: "A importância do Trabalho Voluntário contra às Desigualdades Sociais",
        texto: "Atualmente, tem se percebido pela população o impacto e importância de trabalhos sociais no combate a desigualdades sociais, uma ótima notícia que simboliza a solidariedade da sociedade para os mais vulneráveis. A realização de atos voluntários vem se tornando cada vez mais frequente depois da pandemia do Covid-19, onde devido a seus impactos, mais de 33 milhões de brasileiros ficaram sem ter o que comer, demonstrando a urgência de fazer algo em relação à situação, onde em uma demonstração de compaixão, pessoas vem cedendo tempo e dinheiro para ajudar aos que mais necessitam. Outro caso que demonstra o espírito gentil dos brasileiros e um exemplo para o mundo, foi a ajuda para os afetados pelas enchentes no Rio Grande do Sul, que acabaram por devastar muitas casas e famílias, e as deixando em uma situação desesperadora onde inevitavelmente precisariam de auxílio. Portanto, é indispensável que tenhamos conosco esse espírito gentil e empático de ajudar uns aos outros e realizar tais atos solidários, tal ato salva vidas e alivia a alma ao ver os sorrisos de alegria das pessoas, impulsionando essas pessoas para continuar vivendo e também combatendo às desigualdades sociais."
    },
    {
        titulo: "Os problemas da adultização infantil",
        texto: "O problema da adultização infantil na sociedade tem se tornado cada vez mais severos, com crianças e jovens tendo suas vidas afetadas com danos muitas vezes irreparáveis por todo o resto de sua vida. O fato é, com os avanços do meio digital e a facilidade na publicação de conteúdos com objetivos financeiros, se abriu também um mercado de exploração de interesses muito mais amplo, onde adultos espoem crianças e jovens de forma adultizada, seja realizando ações adultas, ou em casos mais graves, ações de teor sexual. O caso ganhou muita repercussão nos tempos recentes graças ao influenciador digital Felca, que denunciou casos de adultização infantil na internet, com um foco maior em outro influenciador, Hytalo Santos, que há anos lucrava com adolescentes em seus vídeos em uma espécie de reality show, onde ele distribuía bebida a vontade e incentivava eles a realizarem coisas de adulto, tudo sendo postado e vendido nas redes sociais, essas crianças que tiveram essa experiência e foram expostas dessa forma podem inclusive achar isso normal, ou seja, a adultização infantil é um problema gravíssimo que além de afetar os jovens de hoje, pode ser também um problema no futuro, quando estes crescerem e se tornarem os próximos adultos. Em virtude de todos esses fatos, é fundamental que esses criminosos sejam devidamente punidos e as crianças ajudadas, que mais casos como esses sejam denunciados e a justiça seja feita por um mundo melhor para nossas crianças."
    },
    {
        titulo: "O Etarismo Na Sociedade",
        texto: "Nos dias de hoje, é normal observar memes e piadas com relação aos nossos idosos, suas dificuldades e realidades sendo difundidas de forma tão negativa que colora com o Etarismo - Preconceito contra as pessoas mais velhas- O que de muitas formas é absurdo e mostra o quão nossa sociedade é falta de empatia e senso de si mesma. A perpetuação dessa realidade dos mais velhos em corroboração com o crescente aumento na expectativa de vida, forma mais idosos que consequentemente precisarão cada vez mais do apoio dos outros, algo que é natural e foge de seu controle ou vontade, por isso, o etarismo atua como uma dificuldade extra, pela dificuldade em ter suas necessidades em relação ao resto da população. Como por exemplo, os pensamentos e ajudas do governo para os idosos muitas vezes é baseado apenas em sentido farmacêutico, tendo falta em relação à inclusão, como por exemplo falta de rampas e corrimãos, academias ao ar livre e entre outros. O perpetuamento desse pensamento nos tempos atuais deve ser combatido, os jovens precisam entender que os idosos, mais experientes tem muitas memórias de vida e sobrevivência merecedora de respeito tanto quanto qualquer outro, como alternativa proponho a adoção de propostas como a abordagem em maior quantidade desses temas nas escolas e principalmente, que nossos pais e mães atentem-se para a criação de seus filhos por um mundo melhor."
    },
    {
        titulo: "Os benefícios da Educação Financeira para os jovens brasileiros",
        texto: "É indispensável que as novas gerações tenham disponibilidade de acesso à educação financeira nas escolas, tendo em vista a necessidade da construção dessa consciência numa sociedade em que 78,5% das famílias estão endividadas. As aulas de educação financeira atuariam como um mecanismo de transmissão de conhecimento útil e prático, colaborando na formação de jovens adultos responsáveis — sendo os jovens adultos os principais alvos dos bancos com cartões de crédito com limites extremamente atrativos — e que não fossem facilmente influenciados por influências consumistas, assim evitando se afundar em dívidas. A efetividade dessa ação não se mostra apenas na diminuição do número de endividados no território nacional, como também um aumento geral na produtividade nacional, impulsionada pela positiva influência da ausência de pagamentos de dívidas, evidenciado pelo estresse e pressão que dispõem os devedores. Sendo assim, é óbvia sua necessidade na nossa grande nação, Brasil, que conta com tamanhas dívidas pela população, a aplicação da educação financeira na educação brasileira forneceria benefícios gerais a sociedade com o combate aos endividamentos e as consequências positivas trazidas por isso."
    },
    {
        titulo: "A Cultura Popular Brasileira",
        texto: "No Brasil, a cultura popular está aparentemente de diversos modos, desde festivais como o carnaval e festa junina, até danças como frevo e o samba, e em todas essas formas, estão representando a identidade brasileira e sua individualidade. A Identidade de um povo é essencial para uma nação, ainda mais para uma com um território tão extenso e multicultural como o Brasil, se faz necessária a formação dessa personalidade nacional para que a sociedade tenha um senso de pertencimento junto com o país e seus cidadãos. Esse senso de pertencimento não é apenas belo, mas de extrema importância, visto que leva a gerar uma empatia maior, combatendo preconceitos e um criando sentimento de patriotismo, além de gerar grandes movimentações econômicas, com shows e eventos, de forma que se torne até parte da vida da população. Algo de tamanhos benefícios são muitas vezes rejeitados por nosso próprio povo, já que como dizia a frase — a grama do vizinho é sempre mais verde que a nossa — que acaba por exaltar a cultura estrangeira, enquanto despreza a própria, não vendo o devido valor da mesma, causando um sentimento de depreciação à própria sociedade em que vive, sentimento que será repassado às próximas gerações."
    },
    {
        titulo: "A Importância do Saneamento Básico para as populações vulneráveis brasileiras",
        texto: " O saneamento básico constitui um conjunto de ações para que alguém tenha uma qualidade de vida suficiente e adequada para as pessoas, que consta também como um direito na constituição brasileira, porém, é uma verdade de que o saneamento básico não é uma realidade para todos, causando assim muitas mortes e consequências. Os problemas causados por falta desse direito são inúmeros, inúmeras populações vulneráveis sofrem com infecções e doenças, dificultando o cotidiano e afetando a situações socio-econômica das famílias, que precisam cuidar de parentes doentes e arcar com os custos e escassez de recursos. Nisso é posto em evidência a importância da implementação do saneamento básico por todo o Brasil, que mudaria em 360° a vida de inúmeras pessoas que terão mais oportunidades e uma vida digna de verdade. Entretanto, os problemas por trás da garantia desse direito são a invisibilidade do sofrimento dessas pessoas que não são tratados com a devida importância pelo governo e mídia, que apesar das limitações de recursos, tem o dever de zelar pela sua população e realizar campanhas e fornecer apoio aos mesmos, até que o direito do saneamento básico seja um direito de todos."
    },
    {
        titulo: "A União Trazida Pelo Esporte",
        texto: "Uma atividade tão comum na sociedade brasileira como o futebol, um esporte famoso e muito praticado no país, desde crianças até adultos, que nos rendeu o título de País do Futebol, ele ocupa seu espaço na mídia mundial e campeonatos como a Copa do Mundo são capazes de fazer as pessoas vibrarem em união independente do lugar e condição socio-econômica .A verdade é que o fator de união e inclusão trazida pelo esporte é imensa, é uma atividade que traz felicidade e diversão, laços são formados entre as crianças jogando bola no campinho do bairro, mesmo que desconhecidas no início, após jogarem juntos algumas vezes eles criam uma relação harmoniosa e benéfica, a competição quando vista de forma pacífica atua como instrumento de desenvolvimento de habilidades e aproximação entre os jogadores. Mas benefícios mentais e sociais não são os únicos a serem alcançados, o esporte é uma atividade física extremamente benéfica para a saúde do corpo, evitando o sedentarismo, aumentando a resistência, condicionamento físico, visão espacial, precisão, sendo essencial em todas as etapas da vida. É evidente a importância do esporte e como ele atua na sociedade, desde crianças podemos praticar esporte em meio a brincadeiras, e quando adultos a importância não diminui, o próprio futebol é uma atividade cultural que foi e vai continuar sendo praticado pelas próximas gerações de crianças, e nosso dever como sociedade é incentivar isso, o esporte é capaz de mudar vidas e deve ser direito do cidadão poder praticá-lo, por isso o estado deve também promover a construção de áreas de esportes e a prática escolar do mesmo."
    }
];

// ABRIR MODAL
function abrirRedacao(i) {
    document.getElementById("modal-titulo").innerText = redacoes[i].titulo;
    document.getElementById("modal-texto").innerText = redacoes[i].texto;
    document.getElementById("modal").style.display = "flex";
}

// FECHAR MODAL
function fecharModal() {
    document.getElementById("modal").style.display = "none";
}

